services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - teamboard_net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - teamboard_net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  database:
    container_name: database
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - teamboard_net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data  
    networks:
      - teamboard_net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  teamboard_net:
    driver: bridge


volumes:
  portainer_data:
  pgdata:
#NOTA: Los volúmenes globales (pgdata y portainer_data) deben ser declarados 
#aqui abajo por los responsables de la Feature 4 y 5.